version: "3.8"

services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - SECRET_KEY=your_secret_key
      - DEBUG=True
      - ALLOWED_HOSTS=127.0.0.1,.localhost
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - DATAUSA_API_BASE_URL=https://datausa.io/api/data
      - ZIRCON_API_BASE_URL=https://zircon.datausa.io/api/data

  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5432"

volumes:
  postgres_data:
