# Use the official Python image from the Docker Hub
FROM python:3.12

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory
WORKDIR /code

# Copy the requirements file into the container
COPY requirements.txt /code/

# Install the dependencies
RUN pip install -r requirements.txt

# Install PostgreSQL client for pg_isready
RUN apt-get update && apt-get install -y postgresql-client

# Copy the rest of the code into the container
COPY . /code/

# Copy the wait script into the container
COPY wait-for-postgres.sh /code/wait-for-postgres.sh

# Ensure the wait script has execute permissions
RUN chmod +x /code/wait-for-postgres.sh

# Copy the .env file into the container
COPY .env /code/.env

# Create staticfiles directory
RUN mkdir /code/staticfiles

# Expose the port the app runs on
EXPOSE 8000

# Set entrypoint
ENTRYPOINT ["/code/wait-for-postgres.sh"]

# Run migrations and the Django development server
CMD ["sh", "-c", "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
