# Generated by Django 5.0.6 on 2024-06-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_state', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
                ('population', models.IntegerField()),
                ('slug_state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleOwnershipData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_vehicles_available', models.IntegerField()),
                ('vehicles_available', models.CharField(max_length=50)),
                ('id_year', models.IntegerField()),
                ('year', models.CharField(max_length=10)),
                ('commute_means_by_gender', models.IntegerField()),
                ('geography', models.CharField(max_length=50)),
                ('id_geography', models.CharField(max_length=20)),
                ('slug_geography', models.CharField(max_length=50)),
                ('households', models.IntegerField()),
            ],
        ),
    ]
