# Generated by Django 5.0.6 on 2024-06-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleownershipdata',
            name='households',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
